# Generated by Django 4.2.8 on 2023-12-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_number_of_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
    ]
