# Generated by Django 4.2.8 on 2023-12-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_booking_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.SmallIntegerField(default=1),
        ),
    ]
